function addMetadataBox(figHandle, metaText, position)
% addMetadataBox
% Purpose:
%   Add a standardized metadata box to a figure for run traceability.
% Inputs:
%   figHandle - Figure handle.
%   metaText  - Metadata text string (supports newline separators).
%   position  - Optional normalized annotation position [x y w h].
% Outputs:
%   None. Adds a styled annotation textbox to the figure.
% Author:
%   J Frusher

    if nargin < 3 || isempty(position)
        position = [0.73 0.70 0.25 0.24];
    end

    annotation(figHandle, 'textbox', position, ...
        'String', metaText, ...
        'EdgeColor', [0.72 0.72 0.72], ...
        'BackgroundColor', [1 1 1], ...
        'FontSize', 8.5, ...
        'FontName', 'Helvetica', ...
        'HorizontalAlignment', 'left', ...
        'VerticalAlignment', 'top', ...
        'Interpreter', 'none', ...
        'Color', [0.15 0.15 0.15]);
end
