function plotAlgorithmOverview(summary)
% plotAlgorithmOverview
% Purpose:
%   Create a standalone docked figure showing the final algorithm flowchart
%   and a compact parameter table for explainability.
% Inputs:
%   summary - Run summary struct from main pipeline.
% Outputs:
%   None. Creates one docked MATLAB figure.

    fig = figure('Color', 'w', 'Name', 'Algorithm Overview: Robust Explainable Optimizer', 'WindowStyle', 'docked');

    ax = axes(fig, 'Position', [0.03 0.52 0.94 0.44]);
    axis(ax, [0 1 0 1]);
    axis(ax, 'off');

    annotation(fig, 'textbox', [0.02 0.95 0.96 0.04], ...
        'String', 'Final Native Algorithm: Scenario-Based Robust Explainable Stop-Time Optimizer', ...
        'EdgeColor', 'none', 'FontWeight', 'bold', 'FontSize', 12, 'HorizontalAlignment', 'center');

    boxes = [ ...
        0.04 0.70 0.16 0.18; ...
        0.24 0.70 0.16 0.18; ...
        0.44 0.70 0.16 0.18; ...
        0.64 0.70 0.16 0.18; ...
        0.84 0.70 0.12 0.18];

    labels = { ...
        'Patient + PK/PD Inputs', ...
        'Generate Stop-Time Candidates', ...
        'Sample Uncertainty Scenarios', ...
        'Compute E[L], CVaR, P(early)', ...
        'Pick Argmin Objective'};

    for i = 1:size(boxes, 1)
        annotation(fig, 'textbox', boxes(i, :), 'String', labels{i}, ...
            'BackgroundColor', [0.94 0.97 1.00], ...
            'EdgeColor', [0.45 0.62 0.86], ...
            'LineWidth', 1.0, ...
            'FontSize', 9.5, ...
            'HorizontalAlignment', 'center', ...
            'VerticalAlignment', 'middle');
    end

    for i = 1:(size(boxes, 1) - 1)
        x1 = boxes(i, 1) + boxes(i, 3);
        y = boxes(i, 2) + boxes(i, 4) / 2;
        x2 = boxes(i + 1, 1);
        annotation(fig, 'arrow', [x1, x2], [y, y], 'Color', [0.3 0.4 0.55], 'LineWidth', 1.3);
    end

    objectiveText = sprintf('Objective: J = E[L] + %.2f * CVaR_{%.2f}(L) + %.1f * P(early)^2', ...
        localField(summary, 'RobustCVaRWeight', 0.75), ...
        localField(summary, 'RobustCVaRAlpha', 0.85), ...
        localField(summary, 'RobustEarlyProbWeight', 35));

    annotation(fig, 'textbox', [0.04 0.58 0.92 0.08], ...
        'String', objectiveText, ...
        'BackgroundColor', [0.97 0.99 0.97], ...
        'EdgeColor', [0.55 0.75 0.55], ...
        'LineWidth', 1.0, ...
        'FontSize', 10.2, ...
        'HorizontalAlignment', 'center', ...
        'VerticalAlignment', 'middle', ...
        'Interpreter', 'none');

    paramData = {
        'Optimizer Mode', localField(summary, 'OptimizerMode', 'robust-explainable');
        'Data Source', localField(summary, 'DataSource', 'n/a');
        'Uncertainty Profile', localField(summary, 'UncertaintyProfile', 'n/a');
        'Target Wake Delay (min)', sprintf('%.2f', localField(summary, 'TargetWakeDelayMin', NaN));
        'Early Penalty Weight', sprintf('%.1f', localField(summary, 'EarlyPenaltyWeight', NaN));
        'CVaR alpha', sprintf('%.2f', localField(summary, 'RobustCVaRAlpha', 0.85));
        'CVaR weight', sprintf('%.2f', localField(summary, 'RobustCVaRWeight', 0.75));
        'Early Prob weight', sprintf('%.1f', localField(summary, 'RobustEarlyProbWeight', 35));
        'Scenario count', sprintf('%d', localField(summary, 'RobustNumScenarios', 120));
        'Candidate count', sprintf('%d', localField(summary, 'RobustNumStopCandidates', 80));
        'Train/Test Cases', sprintf('%d / %d', localField(summary, 'NumCasesTrain', 0), localField(summary, 'NumCasesTest', 0));
        'Run Timestamp', char(localField(summary, 'RunTimestamp', datestr(now, 'yyyy-mm-dd HH:MM')))
    };

    uitable(fig, ...
        'Data', paramData, ...
        'ColumnName', {'Parameter', 'Value'}, ...
        'ColumnEditable', [false false], ...
        'ColumnWidth', {250 300}, ...
        'RowName', [], ...
        'Position', [90 40 730 300], ...
        'FontSize', 9.5);

    annotation(fig, 'textbox', [0.04 0.02 0.92 0.04], ...
        'String', 'Interpretation: The selected stop-time minimizes expected loss while explicitly controlling early-wake tail-risk under uncertainty.', ...
        'EdgeColor', 'none', 'FontWeight', 'bold', 'FontSize', 9.5, 'HorizontalAlignment', 'center');
end

function value = localField(s, fieldName, defaultValue)
    if isfield(s, fieldName)
        value = s.(fieldName);
    else
        value = defaultValue;
    end
end
