function out = plotStakeholderSimpleAlgorithm(projectRoot)
% plotStakeholderSimpleAlgorithm
% Purpose:
%   Create a super-simple stakeholder figure that explains the current
%   algorithm in plain language for non-technical audiences.
% Inputs:
%   projectRoot - Optional repository root path.
% Outputs:
%   out - Struct with figure handle and exported output paths.

    if nargin < 1 || strlength(string(projectRoot)) == 0
        projectRoot = fileparts(fileparts(mfilename('fullpath')));
    end

    dataDir = fullfile(projectRoot, 'data');
    figDir = fullfile(projectRoot, 'figures');

    summary = localReadDataSummary(dataDir);

    fig = viz.createFigure('Color', 'w', 'Name', 'Simple Algorithm Overview');

    annotation(fig, 'textbox', [0.04 0.93 0.92 0.05], ...
        'String', 'Simple view: how the current algorithm works', ...
        'EdgeColor', 'none', 'FontWeight', 'bold', 'FontSize', 14, ...
        'HorizontalAlignment', 'center');

    annotation(fig, 'textbox', [0.06 0.86 0.88 0.06], ...
        'String', ['Important: this model does not estimate surgery end time from physiology. ', ...
                   'It uses expected surgery end time as an input, then predicts wake timing and recommends when to stop anesthetic.'], ...
        'BackgroundColor', [1.00 0.98 0.90], ...
        'EdgeColor', [0.85 0.75 0.45], ...
        'LineWidth', 1.0, ...
        'FontSize', 10.5, ...
        'HorizontalAlignment', 'left', ...
        'VerticalAlignment', 'middle');

    boxes = [ ...
        0.08 0.58 0.24 0.20; ...
        0.38 0.58 0.24 0.20; ...
        0.68 0.58 0.24 0.20];

    labels = { ...
        sprintf(['Inputs\n\n', ...
                 '• Age, weight, BMI, height, LBM\n', ...
                 '• Infusion rate\n', ...
                 '• Expected surgery end time']), ...
        sprintf(['Model step\n\n', ...
                 'Simulate drug effect-site concentration\n', ...
                 'through time and test stop-time options']), ...
        sprintf(['Outputs\n\n', ...
                 '• Predicted wake time\n', ...
                 '• Recommended stop time\n', ...
                 '• Safety-aware delay target'])};

    fillColors = [ ...
        0.93 0.97 1.00; ...
        0.95 1.00 0.95; ...
        1.00 0.96 0.93];

    edgeColors = [ ...
        0.45 0.62 0.86; ...
        0.48 0.70 0.48; ...
        0.84 0.56 0.32];

    for i = 1:3
        annotation(fig, 'textbox', boxes(i, :), ...
            'String', labels{i}, ...
            'BackgroundColor', fillColors(i, :), ...
            'EdgeColor', edgeColors(i, :), ...
            'LineWidth', 1.2, ...
            'FontSize', 10.2, ...
            'HorizontalAlignment', 'left', ...
            'VerticalAlignment', 'middle');
    end

    for i = 1:2
        x1 = boxes(i, 1) + boxes(i, 3);
        y = boxes(i, 2) + boxes(i, 4) / 2;
        x2 = boxes(i + 1, 1);
        annotation(fig, 'arrow', [x1 x2], [y y], 'Color', [0.30 0.35 0.45], 'LineWidth', 1.6);
    end

    dataText = sprintf([ ...
        'Available data in this workspace\n', ...
        '• Cases loaded: %d\n', ...
        '• Physiological fields: Age, WeightKg, BMI, HeightCm, LBM\n', ...
        '• Timing fields: SurgeryDurationMin, ObservedWakeDelayMin\n', ...
        '• Infusion field: InfusionRateMgPerMin'], ...
        summary.NumCases);

    annotation(fig, 'textbox', [0.08 0.30 0.56 0.20], ...
        'String', dataText, ...
        'BackgroundColor', [0.98 0.98 0.98], ...
        'EdgeColor', [0.75 0.75 0.75], ...
        'LineWidth', 1.0, ...
        'FontSize', 9.8, ...
        'HorizontalAlignment', 'left', ...
        'VerticalAlignment', 'middle');

    takeaway = sprintf([ ...
        'Takeaway\n\n', ...
        'This is a wake-timing optimization model.\n', ...
        'If you want surgery end-time prediction from\n', ...
        'physiology alone, we can add a separate\n', ...
        'duration-prediction model.']);

    annotation(fig, 'textbox', [0.68 0.30 0.24 0.20], ...
        'String', takeaway, ...
        'BackgroundColor', [1.00 1.00 1.00], ...
        'EdgeColor', [0.20 0.20 0.20], ...
        'LineWidth', 1.2, ...
        'FontSize', 10.0, ...
        'FontWeight', 'bold', ...
        'HorizontalAlignment', 'left', ...
        'VerticalAlignment', 'middle');

    if ~exist(figDir, 'dir')
        mkdir(figDir);
    end
    stamp = datestr(now, 'yyyymmdd_HHMMSS');
    outDir = fullfile(figDir, sprintf('simple_algorithm_%s', stamp));
    if ~exist(outDir, 'dir')
        mkdir(outDir);
    end

    pngPath = fullfile(outDir, 'simple_algorithm_plot.png');
    figPath = fullfile(outDir, 'simple_algorithm_plot.fig');

    try
        exportgraphics(fig, pngPath, 'Resolution', 300);
    catch
        saveas(fig, pngPath);
    end
    savefig(fig, figPath);

    out = struct();
    out.Figure = fig;
    out.OutputDirectory = outDir;
    out.PNGPath = pngPath;
    out.FIGPath = figPath;
    out.NumCases = summary.NumCases;

    utils.logger('INFO', sprintf('Saved simple stakeholder algorithm plot to: %s', outDir));
end

function summary = localReadDataSummary(dataDir)
    summary = struct();
    summary.NumCases = 0;

    candidates = {fullfile(dataDir, 'testPatients.csv'), fullfile(dataDir, 'trainPatients.csv')};
    for i = 1:numel(candidates)
        if exist(candidates{i}, 'file')
            try
                t = readtable(candidates{i});
                summary.NumCases = height(t);
                return;
            catch
            end
        end
    end
end
